// For testing purposes, until we start setting up more of our routes on the backend

export const citiesOrCounties = [
  'Hawthorne',
  'Aurora',
  'Albuquerque',
  'Yuba (county)',
  'Lancaster',
  'Macon',
  'Los Banos',
  'Oceanside',
  'Modesto',
  'Manchester',
  'Williston',
  'Charlotte',
  'Victoria',
  'Milwaukee',
  'Virginia Beach',
  'High Point',
  'Campbell',
  'Inkster',
  'Hialeah',
  'Omaha',
  'Miami',
  'Miami Gardens',
  'Perris',
  'Medford',
  'Irvington',
  'Prince William County',
  'Newport News',
  'Fort Myers',
  'Olanta',
  'Tolleson',
  'Georgetown',
  'Lubbock',
  'Falls Church',
  'Pleasantville',
  'Williamsburg',
  'Wausau',
  'Livingston',
  'West New York',
  'Albany',
  'Baton Rouge',
  'Atlantic City',
  'Gretna',
  'Richmond',
  'Phenix City',
  'Pink Hill',
  'Newton',
  'Morrisville',
  'Chelsea',
  'Davidson County',
  'Miami Township',
  'Saint Petersburg',
  'Brownsville',
  'Surprise',
  'Hopkinsville',
  'El Paso',
  'Camden',
  'Nesconset',
  'Texas City',
  'Farmville',
  'Walla Walla',
  'Yakima County',
  'Many',
  'Arvada',
  'Wilmer',
  'Ludington',
  'Ludlow',
  'Evansville',
  'Moore County',
  'Smyrna',
  'Millington',
  'Stamford',
  'Downers Grove',
  'Ashley',
  'Horry County',
  'Midwest City',
  'Sanford',
  'Cornelius',
  'Perry',
  'Cut Bank',
  'Northwoods',
  'Kingston',
  'Canoga Park',
  'Xenia',
  'Navassa',
  'Lamar',
  'Malad',
  'Moorestown',
  'Amherst',
  'Natchitoches',
  'Brandywine',
  'Carter County',
  'Nashua',
  'Wittman',
  'Gulfport',
  'Oroville',
  'Mccall',
  'Great Kills',
  'Oracle',
  'Millersville',
  'Eaton',
  'Warminster',
  'Cade',
  'Windham',
  'Black Mountain',
  'Collingdale',
  'Westwego (Avondale)',
  'Claiborne',
  'Washington Township',
  'New Milford',
  'Wesley Chapel',
  'Hoke County',
  'Attleboro',
  'Casco',
  'East Price Hill',
  'Hickory Hill',
  'Gautier',
  'Roswell',
  'Kettering',
  'Talladega',
  'Pawtucket',
  'Haverhill',
  'Wheeling',
  'Desert Hot Springs',
  'Mims',
  'Warren County',
  'Putnam',
  'Pembroke Pines',
  'Miramar',
  'Harvest',
  'Sherwood',
  'Chester County',
  'Round Rock',
  'Fort Bend County',
  'Youngstown',
  'Altavista',
  'Ellicott City',
  'Daytona',
  'Malta',
  'New London',
  'Niceville',
  'New Berlin',
  'Fountain',
  'El Centro',
  'Olive Branch',
  'Magee',
  'Crane Hill',
  'Stratford',
  'Springs',
  'Yorkville',
  'Laporte',
  'Ecorse',
  'Pelzer',
  'Yankton',
  'District Heights',
  'Lakewood',
  'Red Bank',
  'Robertsville',
  'Riverton',
  'Vestavia Hills',
  'Port Gibson',
  'Onalaska',
  'Swannanoa',
  'Greenbrier County',
  'Blue Springs',
  'Lebanon',
  'Loxahatchee',
  'Somerset',
  'Castalia',
  'Dearborn',
  'Cocoa',
  'Clarkdale',
  'Miami-dade',
  'Banning',
  'Piqua',
  'Caddo Parish',
  'Thurston (county)',
  'Springfield Township',
  'Brisbane',
  'Granite City',
  'Warsaw',
  'Madison (Fitchburg)',
  'Montezuma',
  'Dolton',
  'Agawam',
  'Prichard',
  'Mcallen',
  'East Amherst',
  'New Castle',
  'Hilton Head',
  'Highlands Ranch',
  'Idaho Springs',
  'Ionia County',
  'Girardville',
  'Baldwin',
  'Porterville',
  'Groveland',
  "Lee's Summit",
  'Mount Vernon',
  'Ozark',
  'Mc Cool',
  'Catasauqua',
  'Bloomfield Township',
  'Flanders',
  'Summerton',
  'Martinez',
  'Mustang',
  'Stull',
  'Bend',
  'Mulga',
  'La Mirada',
  'Plano',
  'East Saint Louis',
  'El Dorado',
  'Willoughby',
  'Henderson County',
  'Palmyra',
  'Gloucester City',
  'Clinton Township',
  'Calloway County',
  'Waynesburg',
  'Appleton',
  'Maplewood',
  'Meeker',
  'Pike County',
  'Uhrichsville',
  'Stuart',
  'Greenacres',
  'Hazel Park',
  'Mentor-on-the-Lake',
  'O Fallon',
  'Forrest County',
  'Bluefield',
  'Salina ',
  'Robeson County',
  'Naperville',
  'Baxter',
  'Calumet City',
  'Birmingham (Forestdale)',
  'Joint Base Elmendorf-richardson',
  'Kenmore',
  'Forsyth County',
  'Richmond (Richmond Township)',
  'Conneaut',
  'Avella',
  'Zebulon',
  'Marshall',
  'Sunset Harbor',
  'Terrebonne Parish',
  'Knox County',
  'Autaugaville',
  'Steelton',
  'Carson',
  'West Richland',
  'Casselberry',
  'Cullman',
  'Royal Oak',
  'Eatonville',
  'Clawson',
  'Spencer',
  'Nuevo',
  'Labelle',
  'Natchez',
  'Florence County',
  'Norristown (East Norriton)',
  'Kernersville',
  'Fulton County',
  'El Monte',
  'Ashford',
  'Hoopeston',
  'Bessemer (Hueytown)',
  'East Hampton',
  'Middleboro (Middleborough)',
  'Summerville',
  'Early',
  'Bowie County',
  'Mount Holly Township',
  'Russell (county)',
  'Poe',
  'Sugar Land',
  'Winona',
  'Eatontown',
  'Santa Fe County',
  'Ridgeland',
  'Eden',
  'Ririe',
  'Browns Summit',
  'Bald Knob',
  'Ferndale',
  'Parsippany',
  'Stevens County',
  'Newnan',
  'Benton County',
  'Foley',
  'Unicoi County',
  'Rome',
  'Franklin Furnace',
  'Lyon County',
  'Lapeer',
  'Letcher County',
  'Eaton Rapids',
  'Charleston (Cross Lanes)',
  'New Kensington',
  'Jim Wells (county)',
  'Carrboro',
  'Lookout Valley',
  'Luverne',
  'Sheldon',
  'Andover',
  'Mabelvale',
  'West Columbia',
  'Rockcastle County',
  'Yazoo City',
  'Duxbury',
  'Five Points',
  'Owens Cross Roads',
  'Jacks Creek',
  'Jamestown',
  'Fort Hood',
  'Sulphur Springs',
  'Fridley',
  'Londonderry',
  'Westwego (Bridge City)',
  'East St. Louis',
  'Walls',
  'Waverly',
  'Evans',
  'Sarasota County',
  'Pickens',
  'Hallsville',
  'Granite Falls',
  'Burgaw',
  'Glenwood Springs',
  'Palos Heights',
  'Morehead City',
  'Utica',
  'Nettleton',
  'Edgemoor',
  'Milwaukie',
  'Salton City',
  'Kirkland',
  'Wirtz',
  'Humble',
  'Vincennes',
  'Gardiner',
  'Griffin',
  'Verona',
  'Greenup',
  'Carleton',
  'Wheat Ridge',
  'Hempstead',
  'Sewell',
  'Santa Barbara',
  'Darrow',
  'Glenside',
  'Beloit',
  'Valrico',
  'Midland County',
  'Spanish Springs',
  'Rosalia',
  'Pelham',
  'Wahiawa',
  'Livingston County',
  'Lindon',
  'Hopewell Township',
  'Homewood',
  'Coldiron',
  'Rutherford',
  'LaGrange',
  'Gordo',
  'Derry',
  'Chaves County',
  'Inwood',
  'Honea Path',
  'Hockessin',
  'Brinkley',
  'Earlimart',
  'Nebo',
  'Plover',
  'Pacific',
  'Plattsmouth',
  'Olivehurst',
  'Austintown',
  'Hamersville',
  'Muldrow',
  'Maynard',
  'Belgrade',
  'Kings Beach',
  'Lewis And Clark County',
  'Charlotte County',
  'Seagrove',
  'Zellwood',
  'Tiffin',
  'Inver Grove Heights',
  'Laurel Hill',
  'Deerfield',
  'Jeff Davis County',
  'Norristown',
  'Lebec',
  'Boerne',
  'Weslaco',
  'Purcellville',
  'Natrona County',
  'Cowley County',
  'Ellsworth',
  'Salt Springs',
  'Roxboro',
  'Jefferson Davis County',
  'Ironwood',
  'Evesham Township',
  'Hoquiam',
  'Mcpherson County',
  'Hays County',
  'Paducah',
  'Bolivar',
  'Lutz',
  'Pilot Mountain',
  'Hinesville',
  'Columbia Heights',
  'Pawleys Island',
  'Los Angeles County',
  'Sparta',
  'Jemez Pueblo (Jemez)',
  'Tahoka',
  'Las Palomas',
  'Luzerne',
  'Fruitridge',
  'Bel Ridge',
  'Sauk Village',
  'Minneapolis (Columbia Heights)',
  'Gattman',
  'Wiscasset',
  'Fort Madison',
  'Beaufort County',
  'Broken Arrow ',
  'Valdese',
  'Walkertown',
  'Pendleton',
  'Carolina Forest',
  'East Peoria',
  'Hamblen County',
  'Forest Grove',
  'Hydesville',
  'Delaware',
  'Edison',
  'Charlestown',
  'Bastrop County',
  'New Baltimore (Chesterfield)',
  'Brookhaven',
  'Shelton (Skokomish)',
  'Mason County',
  'Rhinelander',
  'Citra',
  'Sheridan County',
  'Indian Lake',
  'New Ulm',
  'Ravenswood',
  'Altus',
  'Cabazon',
  'Dalton Township',
  'Lithia Springs',
  'Pleasant Garden',
  'Randolph',
  'Nitro',
  'Fort Benning',
  'El Jebel',
  'Blades',
  'Spanish Fort',
  'Saint Louis (Berkeley)',
  'East Hartford',
  "Lady's Island",
  'Guntersville',
  'Centreville',
  'Water View',
  'Flora',
  'Stopover',
  'Creswell',
  'Royalton',
  'Estero ',
  'Lenexa',
  'Gerber',
  'Summit',
  'Haysville',
  'Drexel Hill',
  'Statham',
  'Boggs',
  'Winder',
  'Duncansville',
  'Widener',
  'Grant',
  'Ash',
  'Burnet County',
  'Masardis',
  'Center Line',
  'Cheatham County',
  'Centuria',
  'Tybee Island',
  'Carlyle',
  'New Kent County',
  'Desoto County',
  'Spink County',
  'Hawthorn Woods',
  'Napa County',
  'Saline',
  'Islip',
  'Cantwell',
  'Wanaque',
  'Ooltewah',
  'Hertford',
  'Canastota',
  'Gallatin County',
  'Lackawanna',
  'Tamaqua',
  'Cerro Gordo',
  'Ross County',
  'Bellbrook',
  'Roy',
  'Cedar City',
  'Medway',
  'New Orleans (Carrollton)',
  'Northumberland County',
  'Wildomar',
  'Perkinston',
  'Nanakuli',
  'Saratoga Springs',
  'Wadmalaw Island',
  'Laveen',
  'Chadwicks',
  'West Alton',
  'Louisiana Avenue',
  'Antwerp',
  'Richton Park',
  'Sharon Hill',
  'Mountain Iron',
  'Durango',
  'Keokuk County',
  'Greenwood Village',
  'Redmond',
  'Brasher Falls',
  'Doland',
  'Haddam',
  'Carroll',
  'Catskill',
  'Caryville',
  'Ottawa County',
  'White Bear Lake',
  'East Liberty',
  'Castle Rock',
  'San Clemente',
  'Argyle',
  'Redwood Valley',
  'Mount Gilead',
  'Kalkaska County',
  'Spaulding County',
  'Setauket',
  'Grapeville',
  'Cadiz',
  'Hull',
  'Constantia',
  'Dunmor',
  'Uehling',
  'Eddy',
  'Whiteville',
  'Hatfield',
  'Walsenburg',
  'Newfield',
  'Brewer',
  'Takoma Park',
  'Taunton',
  'Massena',
  'Hicksville',
  'Lugoff',
  'Plain',
  'Yucca Valley',
  'Los Gatos',
  'San Gabriel',
  'Strawberry Plains',
  'Atascocita',
  'Wyckoff',
  'Circle',
  'Fresno County',
  'Belton',
  'Poynette',
  'Hatboro',
  'Cherryville',
  'Lawndale',
  'Belmont County',
  'South Glens Falls',
  'Losantville',
  'Coram',
  'Bradley County',
  'La Crosse County',
  'Chino',
  'Swatara Township',
  'Poca',
  'Trafford',
  'Hope Valley',
  'Kings County',
  'Liberty Township',
  'Eau Claire County',
  'Laton',
  'Libby',
  'Cottonwood Heights',
  'Guadalupe County',
  'Monona County',
  'Palm River',
  'Fort Lauderdale ',
  'Pigeon Forge',
  'Albany ',
  'Joppa',
  'Pacific Grove',
  'Ocean Township',
  'Roseboro',
  'Saltsburg',
  'North Andover',
  'Conewango',
  'Stanley',
  'Revere',
  'Ellenburg',
  'Turtle Creek',
  'Weatherford',
  'University Park',
  'Lorman',
  'Fairlea',
  'Stone',
  'Elmhurst',
  'Dinwiddie',
  'Roebuck',
  'La Habra',
  'Calypso',
  'Hadley',
  'Batavia',
  'Bethany',
  'West Greenwich',
  'Smiths Grove',
  'Adger',
  'Pound',
  'Fremont County',
  'Malibu',
  'Otis',
  'Fieldbrook',
  'Klamath (county)',
  'Wenham',
  'Taney County',
  'Ellisville',
  'Brevard County',
  'Beverly',
  'Tuskegee',
  'Hobe Sound',
  'Universal City',
  'Leslie County',
  'Sagamore Hills',
  'Oelwein',
  'Chili',
  'Kalihi',
  'Schererville',
  'Mojave (county)',
  'Lima',
  'Panorama City',
  'Watson',
  'Fruitvale',
  'Furman',
  'West Turin',
  'North Providence',
  'Vassar',
  'Munising',
  'Sloan',
  'Davis Islands',
  'Wappingers Falls',
  'Raleigh County',
  'Metolius',
  'Kemah',
  'Clinton (Turah)',
  'Crystal Springs',
  'Mill Valley',
  'Galax',
  'Fairhaven',
  'Westwood',
  'Coos County',
  'Lake Ridge',
  'Beebe Plain',
  'Guthrie',
  'Muhlenberg County',
  'Sharp County',
  'Sylacauga',
  'Loganton',
  'Cambridge City',
  'Mccarthy',
  'Hoosick Falls',
  'Fort Mohave',
  'Apollo',
  'Cadillac',
  'Dix',
  'Folly Beach',
  'Newcastle',
  'Blitchton',
  'Carrollton',
  'Pace',
  'Shafter',
  'Galveston (county)',
  'Frisco',
  'Allegany',
  'Round Lake',
  'Fanning Springs',
  'Bradford',
  'Bonneville County',
  'Price',
  'Essexville',
  'Louisburg',
  'Pottsville',
  'Diamond',
  'Chalfont',
  'Elkton',
  'Dry Creek',
  'Hewitt',
  'Holstein',
  'Espy',
  'East Longmeadow',
  'Cooper County',
  'Columbus (county)',
  'Madison (county)',
  'Deming',
  'Yale (Lynn Township)',
  'La Follette',
  'Gotha',
  'Boone (county)',
  'Colbert',
  'Crawfordville',
  'Seattle (Lake City)',
  'Jackson (county)',
  'Provo',
  'Washington (county)',
  'Richgrove',
  'Elkhorn City',
  'Rockbridge (county)',
  'Nowata (county)',
  'Clallam (county)',
  'Carman',
  'Middlebury',
  'Mills',
  'Webb City',
  'Vassalboro',
  'Parmer (county)',
  'Bluffdale',
  'Helper',
  'Dahlonega',
  'Greenwell Springs',
  'Beaufort (Ladys Island)',
  'Tampa (Temple Terrace)',
  'Crofton',
  'Accokeek',
  'Clintonville',
  'Eliot',
  'Blue Ridge',
  'Mobile (county)',
  'Watsontown',
  'Pullman',
  'Marion (county)',
  'Seattle (Tukwila)',
  'Vine Grove',
  'Nikiski',
  'El Paso (county)',
  'Parkman',
  'Floyd (county)',
  'Littlefield (Beaver Dam)',
  'Marlborough (Marlboro)',
  'Fort Myers (San Carlos Park)',
  'Fort Worth (Saginaw)',
  'Wardsboro',
  'Fruitland Park',
  'Centereach',
  'Hill Afb',
  'Bledsoe',
  'Martin (county)',
  'Readfield',
  'Stamping Ground',
  'Rexville',
  'Demotte',
  'Winnetka',
  'Saint Louis (Affton)',
  'Craighead (county)',
  'Jack (county)',
  'Byram',
  'Weld (county)',
  'Ellis',
  'Mason City',
  'Douglas (county)',
  'Triangle',
  'Rainsville (Shiloh)',
  'Holdrege',
  'Marlinton',
  'Gaston (county)',
  'Lamesa',
  'Grand Bay',
  'Decaturville',
  'Smith (county)',
  'Gillette',
  'Osseo (Maple Grove)',
  'Uncasville',
  'St Petersburg',
  'Ballwin',
  'Wayne (county)',
  'Manheim',
  'Bennett',
  'Lake Forest',
  'Horseheads',
  'Constable',
  'Cincinnati (Walnut Hills)',
  'Guerneville',
  'Lyon (county)',
  'Dearing',
  'Oneida',
  'Zavalla',
  'Ionia (county)',
  'The Colony',
  'DeSoto',
  'Adelanto',
  'Highland (county)',
  'Williamsfield',
  'Northville (Edinburg)',
  'Forestdale',
  'Mastic Beach',
  'Sedgwick (county)',
  'Rosenberg',
  'Grain Valley',
  'Toutle',
  'West Yarmouth',
  'Plainview',
  'Chavies',
  'Taswell',
  'Brown (county)',
  'Wise (county)',
  'Washoe (county)',
  'Albert Lea (Oakland)',
  'Buchanan (county)',
  'Holmes (county)',
  'McKinney',
  'Cato',
  'Palermo',
  'Allakaket',
  'Blairs Mills',
  'Monona',
  'Polk City',
  'Hamptonville',
  'Yell County',
  'Hanceville',
  'Randolph County',
  'Rustburg',
  'Ennis',
  'Rockville Centre',
  'Lockbourne',
  'Penngrove',
  'Shoshoni',
  'Little Egg Harbor Twp',
  'Rowletts',
  'Premier',
  'Willow',
  'Red River',
  'Swans Island',
  'New Franklin',
  'Ahsahka',
  'Bottineau (county)',
  'Skidmore',
  'Stanaford',
  'Clinton (Kirkland)',
  'Canonsburg',
  'Beachwood (Warrensville Heights)',
  'Hartford City',
  'Torrington',
  'Rowland Heights',
  'Paauilo',
  'Philpot',
  'Healy',
  'Albany (Colonie)',
  'Land O Lakes',
  'Nocona',
  'Sallisaw',
  'Ronkonkoma',
  'Sussex County',
  'Shungnak',
  'Pacific Beach',
  'Des Peres',
  'Lake Jackson',
  'East Palatka',
  'Narragansett',
  'Ireland',
  'Almond',
  'Hoosick',
  'Malin',
  'Missoula County',
  'North Babylon',
  'Hood County',
  'Allenstown',
  'Lonoke',
  'Ballard County',
  'Walkerton',
  'Wading River',
  'Waupaca',
  'Indiahoma',
  'Eagle Pass',
  'Bedford Park',
  'Duck',
  'Cohoes',
  'Ham Lake',
  'Carbonville',
  'Centre Hall',
  'Lucas County',
  'Algonquin',
  'Groveport',
  'Richwood',
  'Shoshone County',
  'Madera County',
  'Minneapolis (New Hope)',
  'Goddard',
  'Roberta',
  'Wadesville',
  'Burke County (county)',
  'Belen',
  'Poway',
  'Rolla',
  'Woodlyn',
  'Round Lake (Volo)',
  'New Hyde Park',
  'Bagley',
  'Middlesex (county)',
  'Falconer',
  'Winston Salem',
  'New Kent (county)',
  'Milladore',
  'Molino',
  'Shavertown (Jackson Twp)',
  'Casa Grande',
  'Belle',
  'Mission (Palmview)',
  'Chicago (Englewood)',
  'Ludowici',
  'Middleport',
  'Frederica',
  'Fort Lauderdale (Weston)',
  'Roca',
  'Oregon City (Redland)',
  'Saint Johns (Julington Creek)',
  'Skiatook',
  'Mexican Hat',
  'Alma',
  'Pine Mountain',
  'Fultondale',
  'New Brockton',
  'Cincinnati (Deer Park)',
  'Truth Or Consequences',
  'Oreland',
  'Socorro',
  'Vincent',
  'Fort Worth (Watauga)',
  'Schertz',
  'Middleport (Royalton)',
  'Byars (Rosedale)',
  'Big Springs',
  'Port Byron',
  'Carter (county)',
  'Swords Creek',
  'Lincolnshire',
  'Mobile (Chickasaw)',
  'Guymon',
  'Caswell (county)',
  'Williamsport (Center City)',
  'Willet',
  'Sellersburg',
  'Trenton (Hamilton)',
  'Seattle (Capitol Hill)',
  'Marina Del Rey',
  'Highland Mills',
  'Labette (county)',
  'Westbury (New Cassel)',
  'Saint Louis (Pagedale)',
  'Barry County (county)',
  'Lorton',
  'Hoffman Estates',
  'Appleton (Grand Chute)',
  'Gouldsboro (Thornhurst)',
  'Anamosa',
  'Wardell',
  'Hahnville',
  'Dushore (Wilmot Township)',
  'Saint Lucie (county)',
  'Cleveland (Lyndhurst)',
  'Moscow Mills',
  'Sagamore Beach',
  'Buffalo (Cheektowaga)',
  'Stafford (county)',
  'Reading (Sinking Spring)',
  'Halifax (county)',
  'Halethorpe (Lansdowne)',
  'Mc Lean (McLean)',
  'Dilworth',
  'Castleton On Hudson',
  'Center Moriches',
  'Jessamine (county)',
  'Cincinnati (Cumminsville)',
  'Rose Hill',
  'Pittsburgh (Swissvale)',
];

export const states = [
  'Delaware',
  'Georgia',
  'Michigan',
  'Louisiana',
  'Florida',
  'Wisconsin',
  'Rhode Island',
  'North Dakota',
  'Idaho',
  'Maine',
  'Pennsylvania',
  'Tennessee',
  'Indiana',
  'Kentucky',
  'Alaska',
  'Nevada',
  'South Dakota',
  'California',
  'Colorado',
  'North Carolina',
  'New Mexico',
  'Mississippi',
  'Arizona',
  'Nebraska',
  'Hawaii',
  'Oregon',
  'Illinois',
  'Washington',
  'Maryland',
  'Virginia',
  'New Hampshire',
  'Arkansas',
  'Wyoming',
  'Oklahoma',
  'Utah',
  'New York',
  'South Carolina',
  'Texas',
  'Alabama',
  'Connecticut',
  'West Virginia',
  'Minnesota',
  'Iowa',
  'New Jersey',
  'Kansas',
  'Montana',
  'Vermont',
  'District of Columbia',
  'Ohio',
  'Missouri',
  'Massachusetts',
];

export const gunTypes = [
  '45 Auto',
  '20 gauge',
  '44 Mag',
  '16 gauge',
  '300 Win',
  '22 LR',
  '410 gauge',
  '30-06 Spr',
  '357 Mag',
  '308 Win',
  '9mm',
  'Shotgun',
  'Rifle',
  'Other',
  '380 Auto',
  '223 Rem [AR-15]',
  '25 Auto',
  '7.62 [AK-47]',
  'Handgun',
  '32 Auto',
  '12 gauge',
  '38 Spl',
  '40 SW',
  '10mm',
  '30-30 Win',
  '28 gauge',
];

export const houseDistricts = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59',
  '60',
  '61',
  '62',
  '63',
  '64',
  '65',
  '66',
  '67',
  '68',
  '69',
  '70',
  '71',
  '72',
  '73',
  '74',
  '75',
  '76',
  '77',
  '78',
  '79',
  '80',
  '81',
  '82',
  '83',
  '84',
  '85',
  '86',
  '87',
  '88',
  '89',
  '90',
  '91',
  '92',
  '93',
  '94',
  '95',
  '96',
  '97',
  '98',
  '99',
  '100',
  '101',
  '102',
  '103',
  '104',
  '105',
  '106',
  '107',
  '108',
  '109',
  '110',
  '111',
  '112',
  '113',
  '114',
  '115',
  '116',
  '117',
  '118',
  '119',
  '120',
  '121',
  '122',
  '123',
  '124',
  '125',
  '126',
  '127',
  '128',
  '129',
  '130',
  '131',
  '132',
  '133',
  '134',
  '135',
  '136',
  '137',
  '138',
  '139',
  '140',
  '141',
  '142',
  '143',
  '144',
  '145',
  '146',
  '147',
  '148',
  '149',
  '150',
  '151',
  '152',
  '153',
  '154',
  '155',
  '156',
  '157',
  '158',
  '159',
  '160',
  '161',
  '162',
  '163',
  '164',
  '165',
  '166',
  '167',
  '168',
  '169',
  '170',
  '171',
  '172',
  '173',
  '174',
  '175',
  '176',
  '177',
  '178',
  '179',
  '180',
  '181',
  '182',
  '183',
  '184',
  '185',
  '186',
  '187',
  '188',
  '189',
  '190',
  '191',
  '192',
  '193',
  '194',
  '195',
  '196',
  '197',
  '198',
  '199',
  '200',
  '201',
  '202',
  '203',
  '204',
  '205',
  '206',
  '207',
  '208',
  '209',
  '210',
  '211',
  '212',
  '214',
  '215',
  '216',
  '217',
  '218',
  '219',
  '303',
  '411',
  '413',
  '503',
  '506',
  '510',
  '511',
  '512',
  '513',
  '514',
  '515',
  '516',
  '517',
  '518',
  '521',
  '524',
  '529',
  '530',
  '533',
  '537',
  '601',
  '602',
  '603',
  '605',
  '608',
  '610',
  '614',
  '615',
  '618',
  '622',
  '623',
  '624',
  '705',
  '708',
  '709',
  '713',
  '714',
  '716',
  '717',
  '718',
  '720',
  '721',
  '723',
  '724',
  '725',
  '726',
  '727',
  '729',
  '801',
  '804',
  '805',
  '808',
  '809',
  '811',
  '813',
  '814',
  '901',
];

export const senateDistricts = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59',
  '60',
  '61',
  '62',
  '63',
  '64',
  '65',
  '66',
  '67',
  '94',
];

export const incidentCharacteristics = [
  'Officer Involved Shooting - subject/suspect/perpetrator killed',
  'Shot - Dead (murder, accidental, suicide)',
  'Possession of gun by felon or prohibited person',
  'Officer Involved Shooting - Officer shot',
  'Defensive Use - Crime occurs, victim shoots subject/suspect/perpetrator',
  'Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )',
  'Home Invasion - Resident killed',
  'Unlawful purchase/sale',
  'Road rage',
  'Home Invasion - No death or injury',
  'Accidental/Negligent Discharge',
  'Thought gun was unloaded',
  'Self-Inflicted (not suicide or suicide attempt - NO PERP)',
  'Accidental Shooting at a Business',
  'Non-Aggression Incident',
  'Defensive Use - Shots fired, no injury/death',
  'Defensive Use - Stand Your Ground/Castle Doctrine established',
  'Child with gun - no shots fired',
  'Officer Involved Shooting - Bystander shot',
  'Gun buy back action',
  'Domestic Violence',
  'Possession (gun(s) found during commission of other crimes)',
  'Bar/club incident - in or around establishment',
  'Murder/Suicide',
  'Defensive Use - Victim stops crime',
  'Attempted Murder/Suicide (one variable unsuccessful)',
  'Officer Involved Shooting - Officer killed',
  'Pistol-whipping',
  'Accidental Shooting - Injury',
  'Home Invasion - subject/suspect/perpetrator injured',
  'Workplace shooting (disgruntled employee)',
  'Police Targeted',
  'Gun shop robbery or burglary',
  'Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)',
  'Defensive Use',
  'Suicide',
  'Concealed Carry License - Perpetrator',
  'Implied Weapon',
  'Brandishing/flourishing/open carry/lost/found',
  'Accidental Shooting - Death',
  'Hunting accident',
  'Child picked up & fired gun',
  'Officer Involved Shooting - Shots fired, no injury',
  'Officer Involved Shooting - subject/suspect/perpetrator surrender at standoff',
  'Shootout (where VENN diagram of shooters and victims overlap)',
  'Guns stolen from law enforcement',
  'Officer Involved Shooting - subject/suspect/perpetrator shot',
  'School Incident',
  'School Shooting - university/college',
  'House party',
  'Institution/Group/Business',
  'Animal shot/killed',
  'Home Invasion - Resident injured',
  'Accidental Shooting',
  'Cleaning gun',
  'Non-Shooting Incident',
  'Gun range/gun shop/gun show shooting',
  'Child injured self',
  'Suicide - Attempt',
  'School Shooting - elementary/secondary school',
  'Concealed Carry License - Victim',
  'Defensive Use - WITHOUT a gun',
  'Playing with gun',
  'Child injured by child',
  'Child killed (not child shooter)',
  'Gang involvement',
  'Drive-by (car to street, car to car)',
  'Drug involvement',
  'Home Invasion',
  'Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff',
  'BB/Pellet/Replica gun',
  'Shots fired, no action (reported, no evidence found)',
  'Child killed by child',
  'Gun at school, no death/injury - university/college',
  'Ghost gun',
  'Political Violence',
  'Mass Murder (4+ deceased victims excluding the subject/suspect/perpetrator , one location)',
  'Shot - Wounded/Injured',
  'Armed robbery with injury/death and/or evidence of DGU found',
  'Spree Shooting (multiple victims, multiple locations)',
  'TSA Action',
  'Defensive Use - Good Samaritan/Third Party',
  'Officer Involved Shooting - Accidental discharge - no injury required',
  'Kidnapping/abductions/hostage',
  'Car-jacking',
  'Hate crime',
  'Shots Fired - No Injuries',
  'Assault weapon (AR-15, AK-47, and ALL variants defined by law enforcement)',
  'ATF/LE Confiscation/Raid/Arrest',
  'Sex crime involving firearm',
  'Gun(s) stolen from owner',
  'Child Involved Incident',
  'Criminal act with stolen gun',
  'Child injured (not child shooter)',
  'Stolen/Illegally owned gun{s} recovered during arrest/warrant',
  'Officer Involved Incident',
  'Home Invasion - subject/suspect/perpetrator killed',
  'Officer Involved Incident - Weapon involved but no shots fired',
  'Child killed self',
  'Gun at school, no death/injury - elementary/secondary school',
  'Officer Involved Shooting - subject/suspect/perpetrator unarmed',
  'ShotSpotter',
  'Defensive use - No shots fired',
  'Officer Involved Shooting - Bystander killed',
  'LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite',
  'Mistaken ID (thought it was an intruder/threat, was friend/family)',
  'Officer Involved Shooting - subject/suspect/perpetrator suicide by cop',
  'Terrorism Involvement',
  'NAV',
];
